### ISSUE TITLE
Cannot build in Ubuntu 22.04 - error: reference to ‘size’ is ambiguous

### ISSUE THREAD

**Issue by andimik** [newspaperman/tsniv2ni#5]
In latest Ubuntu 22.04 compilation fails:

```
$ make
g++    -c -o tsniv2ni.o tsniv2ni.cpp
tsniv2ni.cpp: In function ‘int main(int, char**)’:
tsniv2ni.cpp:65:9: error: reference to ‘size’ is ambiguous
   65 |         size=200;
      |         ^~~~
In file included from /usr/include/c++/11/string:54,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/ios:42,
                 from /usr/include/c++/11/ostream:38,
                 from /usr/include/c++/11/iostream:39,
                 from tsniv2ni.cpp:19:
/usr/include/c++/11/bits/range_access.h:254:5: note: candidates are: ‘template<class _Tp, long unsigned int _Nm> constexpr std::size_t std::size(const _Tp (&)[_Nm])’
  254 |     size(const _Tp (&)[_Nm]) noexcept
      |     ^~~~
/usr/include/c++/11/bits/range_access.h:245:5: note:                 ‘template<class _Container> constexpr decltype (__cont.size()) std::size(const _Container&)’
  245 |     size(const _Container& __cont) noexcept(noexcept(__cont.size()))
      |     ^~~~
tsniv2ni.cpp:28:5: note:                 ‘int size’
   28 | int size;
      |     ^~~~
tsniv2ni.cpp:66:33: error: reference to ‘size’ is ambiguous
   66 |         char* packets= new char[size*188];
      |                                 ^~~~
In file included from /usr/include/c++/11/string:54,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/ios:42,
                 from /usr/include/c++/11/ostream:38,
                 from /usr/include/c++/11/iostream:39,
                 from tsniv2ni.cpp:19:
/usr/include/c++/11/bits/range_access.h:254:5: note: candidates are: ‘template<class _Tp, long unsigned int _Nm> constexpr std::size_t std::size(const _Tp (&)[_Nm])’
  254 |     size(const _Tp (&)[_Nm]) noexcept
      |     ^~~~
/usr/include/c++/11/bits/range_access.h:245:5: note:                 ‘template<class _Container> constexpr decltype (__cont.size()) std::size(const _Container&)’
  245 |     size(const _Container& __cont) noexcept(noexcept(__cont.size()))
      |     ^~~~
tsniv2ni.cpp:28:5: note:                 ‘int size’
   28 | int size;
      |     ^~~~
tsniv2ni.cpp:71:37: error: reference to ‘size’ is ambiguous
   71 |                 inbuf->read(packets,size * 188);
      |                                     ^~~~
In file included from /usr/include/c++/11/string:54,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/ios:42,
                 from /usr/include/c++/11/ostream:38,
                 from /usr/include/c++/11/iostream:39,
                 from tsniv2ni.cpp:19:
/usr/include/c++/11/bits/range_access.h:254:5: note: candidates are: ‘template<class _Tp, long unsigned int _Nm> constexpr std::size_t std::size(const _Tp (&)[_Nm])’
  254 |     size(const _Tp (&)[_Nm]) noexcept
      |     ^~~~
/usr/include/c++/11/bits/range_access.h:245:5: note:                 ‘template<class _Container> constexpr decltype (__cont.size()) std::size(const _Container&)’
  245 |     size(const _Container& __cont) noexcept(noexcept(__cont.size()))
      |     ^~~~
tsniv2ni.cpp:28:5: note:                 ‘int size’
   28 | int size;
      |     ^~~~
tsniv2ni.cpp:75:32: error: reference to ‘size’ is ambiguous
   75 |                 for(int i=0; i<size*188;i+=188) {
      |                                ^~~~
In file included from /usr/include/c++/11/string:54,
                 from /usr/include/c++/11/bits/locale_classes.h:40,
                 from /usr/include/c++/11/bits/ios_base.h:41,
                 from /usr/include/c++/11/ios:42,
                 from /usr/include/c++/11/ostream:38,
                 from /usr/include/c++/11/iostream:39,
                 from tsniv2ni.cpp:19:
/usr/include/c++/11/bits/range_access.h:254:5: note: candidates are: ‘template<class _Tp, long unsigned int _Nm> constexpr std::size_t std::size(const _Tp (&)[_Nm])’
  254 |     size(const _Tp (&)[_Nm]) noexcept
      |     ^~~~
/usr/include/c++/11/bits/range_access.h:245:5: note:                 ‘template<class _Container> constexpr decltype (__cont.size()) std::size(const _Container&)’
  245 |     size(const _Container& __cont) noexcept(noexcept(__cont.size()))
      |     ^~~~
tsniv2ni.cpp:28:5: note:                 ‘int size’
   28 | int size;
      |     ^~~~
make: *** [<eingebaut>: tsniv2ni.o] Fehler 1
```

```
$ make --version
GNU Make 4.3
Gebaut für x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
Lizenz GPLv3+: GNU GPL Version 3 oder später <http://gnu.org/licenses/gpl.html>
Dies ist freie Software: Sie können sie nach Belieben ändern und weiter verteilen.
Soweit es die Gesetze erlauben gibt es KEINE GARANTIE.
```

```
$ g++ --version
g++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by andimik** [comment]
Replacing `size` helped:

```
diff --git a/tsniv2ni.cpp b/tsniv2ni.cpp
index b1c763f..c4370ce 100644
--- a/tsniv2ni.cpp
+++ b/tsniv2ni.cpp
@@ -25,7 +25,7 @@ using namespace std;
 
 istream* inbuf;
 ostream* outbuf;
-int size;
+int tssize;
 bool active=false;
 const char fsync0[]="\xff\x07\x3a\xb6";
 const char fsync1[]="\xff\xf8\xc5\x49";
@@ -62,17 +62,17 @@ int main(int argc, char** argv) {
        }
        inbuf = &cin;
        outbuf = &cout;
-       size=200;
-       char* packets= new char[size*188];
+       tssize=200;
+       char* packets= new char[tssize*188];
        frpd= new char[6140];
        memset(frpd,0x55,6140);
        count=0;
        while(1) {
-               inbuf->read(packets,size * 188);
+               inbuf->read(packets,tssize * 188);
                if(inbuf->fail()) break;
                unsigned char *p;
-               //outbuf->write(packets,size*188);
-               for(int i=0; i<size*188;i+=188) {
+               //outbuf->write(packets,tssize*188);
+               for(int i=0; i<tssize*188;i+=188) {
                                int start=0;
                                /*if((((packets[i+3])&0xC0))!=0x00) {
                                        std::cerr << "encrypted" << std::endl;  
```
